website/models.py
from sqlalchemy.orm import backref
from . import db
from flask_login import UserMixin # custom class that user objects inherit from user mixins
from sqlalchemy.sql import func

# Users have many posts
class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id', ondelete="CASCADE"), nullable=False)
    comments = db.relationship('Comment', backref="post", passive_deletes=False, cascade="all")
    likes = db.relationship("Like", backref="post", passive_deletes=False, cascade="all")

class Comment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id', ondelete="CASCADE"), nullable=False)
    post_id = db.Column(db.Integer, db.ForeignKey('post.id', ondelete="CASCADE"), nullable=False)

class Like(db.Model): 
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id', ondelete="CASCADE"), nullable=False)
    post_id = db.Column(db.Integer, db.ForeignKey('post.id', ondelete="CASCADE"), nullable=False)
    
class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    address = db.Column(db.String(150))
    post_code = db.Column(db.String(8))

    posts = db.relationship('Post', backref="user", passive_deletes=True)
    comments = db.relationship('Comment', backref="user", passive_deletes=True)
    likes = db.relationship('Like', backref="user", passive_deletes=True)

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"

def create_app(): 
    app = Flask(__name__)
    app.config["SECRET_KEY"] = "fgdnjrkflefrfvj"
    # sqlachemy db stored at sqlite.. need to tell flask where it's located
    app.config["SQLALCHEMY_DATABASE_URI"] = f'sqlite:///{DB_NAME}'
    # initialize db by giving it the flask app
    db.init_app(app)

    from .views import views
    from .auth import auth
    from .crud.add import add
    from .crud.delete import delete
    from .crud.update import update

    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(auth, url_prefix="/")
    app.register_blueprint(add, url_prefix="/")
    app.register_blueprint(delete, url_prefix="/")
    app.register_blueprint(update, url_prefix="/")

    from .models import User

    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = "auth.login"
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))
    
    return app

def create_database(app):
    if not path.exists("website/" + DB_NAME):
        db.create_all(app=app)
        print("created Database")

website/auth.py
from flask import Blueprint, render_template, redirect, request, flash, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, logout_user, current_user


auth = Blueprint("auth", __name__)


@auth.route("/login", methods=["GET", "POST"])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email or Password is incorrect.', category='error')

    return render_template("auth/login.html", user=current_user)


@auth.route("/logout")
def logout():
    logout_user()
    flash('Logged out successfully!', category='success')

    return redirect(url_for("views.home"))


@auth.route("/sign-up", methods=["GET", "POST"])
def sign_up():
    if request.method == "POST":
        email = request.form.get("email")
        first_name = request.form.get("first_name")
        address = request.form.get("address")
        post_code = request.form.get("post_code")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")

        user = User.query.filter_by(email=email).first()
        username = User.query.filter_by(first_name=first_name).first()
        if (user):
            flash('Email already exists.', category='error')
        elif (username):
            flash('Please choose another first name.', category='error') 
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif len(password2) <= 0:
            flash("Please confirm your password.", category="error")
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, address=address, post_code=post_code, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("auth/sign_up.html", user=current_user)

website/views.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import current_user
from flask_login.utils import login_required
from sqlalchemy.sql.expression import asc, desc

from website.crud.add import posts_comments
from .models import Comment, Post, User
from . import db


views = Blueprint("views", __name__)

@views.route("/")
def home():
    return render_template("home.html", user=current_user)

@views.route("/discussion")
@login_required
def posts():
    posts = Post.query.order_by(Post.date.desc()).all()
    return render_template("posts.html", user=current_user, posts=posts)

@views.route("/account/my-posts/<first_name>")
@login_required
def my_posts(first_name):
    user = User.query.filter_by(first_name=first_name).first()

    if not user:
        flash("No user with that username exists", category="error")
        return redirect(url_for("views.home"))

    posts = Post.query.filter_by(user_id=user.id).order_by(Post.date.desc()).all()
    print(posts)
    # posts = user.posts
    return render_template("my-posts.html", user=current_user, posts=posts, first_name=first_name)

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block meta %}
    <!-- Required meta tags -->
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    {% endblock %} {% block extra_meta %} {% endblock %} {% block corecss %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='css/main.css')}}"
    />
    <script
      src="https://kit.fontawesome.com/f3bd201d2b.js"
      crossorigin="anonymous"
    ></script>
    {% endblock %} {% block extra_css %} {% endblock %} {% block corejs %}
    <script
      src="https://kit.fontawesome.com/f3bd201d2b.js"
      crossorigin="anonymous"
    ></script>
    {% endblock %} {% block extra_js %} {% endblock %}

    <title>Worlds Best Beer? {% block extra_title %}{% endblock %}</title>
    <link rel="icon" type="image/png" href="../static/img/favicon.png" />
  </head>
  <body>
    <header>
      <div class="hamburger-container">
        <div class="hamburger">
          <span class="hamburger__btn"> </span>
        </div>
      </div>
      <nav>
        <ul class="nav" id="nav">
          <li class="nav__item"><a href="/">Home</a></li>
          {% if user.is_authenticated %}
          <li class="nav__item"><a href="/discussion">Discussion</a></li>
          <div class="dropdown">
            <a class="dropdown__selected">
              Account
              <div class="arrow"></div
            ></a>
            <ul class="dropdown__menu">
              <li class="nav__item">
                <a href="/account/my-posts/{{user.first_name}}">My Posts</a>
              </li>
              <li class="nav__item">
                <a href="/account/my-details/{{user.first_name}}">My Details</a>
              </li>
            </ul>
          </div>

          <li class="nav__item"><a href="/logout">Logout</a></li>

          {% else %}
          <li class="nav__item"><a href="/login">Login</a></li>
          <li class="nav__item">
            <a href="{{ url_for('auth.sign_up') }}">Signup</a>
          </li>
          {% endif %}
        </ul>
      </nav>
    </header>

    {% block page_header %} {% with messages =
    get_flashed_messages(with_categories=true) %} {% if messages %} {% for
    category, message in messages %}
    <div class="alert alert__{{category}}">
      {{ message }}
      <div class="close">x</div>
    </div>
    {% endfor %} {% endif %} {% endwith %} {% endblock %} {% block content %} {%
    endblock %}
    <div class="social-icons">
      <a href="https://www.linkedin.com/in/acr123/">
        <i class="fab fa-linkedin-in fa-2x"></i>
      </a>
      <a href="https://github.com/alexrem1">
        <i class="fab fa-github fa-2x"></i>
      </a>
    </div>

    <footer>&copy; Copyright 2021</footer>
    {% block postloadjs %}
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='js/index.js') }}"
    ></script>
    {% endblock %}
  </body>
</html>

website/templates/home.html
{% extends 'base.html' %} {% block extra_title %}- Home{% endblock extra_title
%} {% block content %}
<video
  src="../static/video/video.mp4"
  muted
  loop
  autoplay
  preload="metadata"
></video>
<header class="home--header">
  <h1>
    Enter the
    <span><a href="/discussion">Discussion</a> </span>
  </h1>
  {% if user.is_authenticated %}
  <h2>
    Welcome
    <span class="home__username"
      ><a href="/account/my-details/{{user.first_name}}"
        >{{user.first_name}}</a
      ></span
    >
    {% endif %}
  </h2>
</header>
<section class="home">
  What is the worlds greatest beer...
  <br /><br />
  We’re starting to see dedication to craft brewing that rivals Europe’s
  enthusiasm for wine.
  <br /><br />
  With a helping hand from you guys, let us know what you think the best beers
  in the world are.
  <br /><br />
  Beer freak or not, these may end up on your bucket—or pint—list.
  <br />
</section>
{% endblock content %}

website/templates/my-details.html
{% extends "base.html" %} {% block extra_title %}- My Details{% endblock
extra_title%} {% block content%}

<section class="details">
  <h1>My Details</h1>
  <div class="details--container">
    <form action="/account/my-details/{{user.first_name}}" method="POST">
      <label for="first_name">First Name</label>
      <input
        type="text"
        name="first_name"
        id="first_name"
        value="{{user.first_name}}"
        disabled
      />
      <label for="email">Email Address</label>
      <input type="text" name="email" id="email" value="{{user.email}}" />
      <label for="address">First Line of Address</label>
      <input type="text" name="address" id="address" value="{{user.address}}" />
      <label for="postcode">Postcode</label>
      <input
        type="text"
        name="post_code"
        id="post_code"
        value="{{user.post_code}}"
      />
      <div class="details__button">
        <button type="submit">
          <a href="/">Cancel</a>
        </button>
        <button type="submit"><a>Update details</a></button>
      </div>
    </form>
  </div>
</section>
{% endblock content%}

website/templates/my-posts.html
{% extends "base.html" %} {% block extra_title %} - {{first_name}}'s Posts{%
endblock extra_title%} {% block content %}
<section class="posts--container">
  <h1>{{first_name}}'s Post History</h1>
  <ul class="posts my--posts">
    {% if not posts %}
    <p>There's no posts yet... Be the first to tell us your favourite beer!</p>
    {% else %} {% for post in posts %}
    <div class="posts__item--container">
      <li class="posts__item">
        {% if user.id == post.user_id%}
        <span class="posts__item__link">
          <a href="/delete-post/{{post.id}}">Delete Post</a></span
        >{%endif%}
        <br />
        {{post.date}} <br /><br />
        {{ post.data }}
        <br />
        {% if user.id in post.likes|map(attribute="post_id")|list %}

        <span class="posts__item__like"
          ><p>{{post.likes|length}}</p>
          <a href="/like-post/{{post.id}}"><i class="fas fa-thumbs-up"></i></a
        ></span>
        {% else %}

        <span class="posts__item__like"
          ><p>{{post.likes|length}}</p>
          <a href="/like-post/{{post.id}}"><i class="far fa-thumbs-up"></i></a
        ></span>
        {% endif %}
      </li>
    </div>

    <div class="posts__comments--container">
      <button class="viewComments">
        View {{post.comments|length}} Comments
      </button>
      <div class="posts__comments">
        {% if not post.comments|length > 0%} There's no comments for this post.
        {%else%} {% for comment in post.comments %}
        <div class="posts__comments__single">
          {{comment.date}}
          <br />
          {{comment.user.first_name}} said: "{{comment.data}}""
          <br />
          {% if user.id == post.user_id%}
          <!-- user.id == comment.user_id or user.id == post.first_name eg if they own commment. above is if they own the post-->
          <a href="/delete-comment/{{comment.id}}">Delete Comment</a>
          {%endif%}
        </div>
        {% endfor %} {%endif%}
      </div>
    </div>

    {% endfor %}{% endif %}
  </ul>
</section>
{% endblock %}

website/templates/posts.html
{% extends "base.html" %} {% block extra_title %}- Discussion{% endblock
extra_title%} {% block content%}

<section class="posts--container">
  <h1>What is the worlds best beer?</h1>
  <ul class="posts">
    {% if not posts %}
    <p>There's no posts yet... Be the first to tell us your favourite beer!</p>
    {% else %} {% for post in posts %}
    <div class="posts__item--container">
      <li class="posts__item">
        <span class="posts__item__link"
          >View {{post.user.first_name}}'s
          <a href="/account/my-posts/{{post.user.first_name}}">
            Post History
          </a>
          <br /></span
        >{% if user.id == post.user_id%}
        <span class="posts__item__link">
          <a href="/delete-post/{{post.id}}">Delete Post</a></span
        >{%endif%} <br />
        Username: {{post.user.first_name}}

        <br />
        Time: {{post.date}} <br />
        <br />
        {{ post.data }}
        <br />

        {% if user.id in post.likes|map(attribute="post_id")|list %}

        <span class="posts__item__like"
          ><p>{{post.likes|length}}</p>
          <a href="/like-post/{{post.id}}"><i class="fas fa-thumbs-up"></i></a
        ></span>
        {% else %}

        <span class="posts__item__like"
          ><p>{{post.likes|length}}</p>
          <a href="/like-post/{{post.id}}"><i class="far fa-thumbs-up"></i></a
        ></span>
        {% endif %}
      </li>

      <form method="POST" action="/discussion/create-comment/{{post.id}}">
        <textarea name="comment" id="comment"></textarea>
        <button type="submit">Add Comment</button>
      </form>
    </div>

    <div class="posts__comments--container">
      <button class="viewComments">
        View {{post.comments|length}} Comments
      </button>
      <div class="posts__comments">
        {% if not post.comments|length > 0 %} There's no comments for this post.
        {%else%} {% for comment in post.comments %}
        <div class="posts__comments__single">
          {{comment.date}}
          <br />
          {{comment.user.first_name}} said: "{{comment.data}}"
          <br />
          {% if user.id == post.user_id%}
          <!-- user.id == comment.user_id or user.id == post.first_name eg if they own commment. above is if they own the post-->
          <a href="/delete-comment/{{comment.id}}">Delete Comment</a>
          {%endif%}
        </div>
        {% endfor %} {%endif%}
      </div>
    </div>

    {% endfor %}{% endif %}
  </ul>
  <form method="POST" action="/discussion">
    <textarea name="post"></textarea>
    <button type="submit">Add Post</button>
  </form>
</section>

{% endblock content %}